[project]
name = "projet4"
version = "0.1.0"
description = ""
authors = [
    {name = "Artur Agababyan", email = "artur.agababyan04@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "scikit-learn",  # uv installera la version la plus récente compatible
    "pandas",        # Nécessaire en prod pour tes DataFrames
    "numpy<2.3"      # CRITIQUE : On force <2.3 ici aussi pour la compatibilité générale
]

# Outils de développement (Analyse, Notebooks, Tests)
[dependency-groups]
dev = [
    "seaborn",
    "shap",
    "matplotlib",
    "ipykernel"
]

# Système de build
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# --- CORRECTION CRUCIALE ---
# Cette section explique à hatchling où trouver ton code (ici, à la racine)
[tool.hatch.build.targets.wheel]
packages = ["."]